AnimalType.create([{ name: 'Perro' },
                   { name: 'Gato' }])

Breed.create([{ name: 'Zaguate', animal_type_id: 1 },
              { name: 'Otra', animal_type_id: 1 },
              { name: 'Dálmata', animal_type_id: 1 },
              { name: 'Beagle', animal_type_id: 1 },
              { name: 'Bóxer', animal_type_id: 1 },
              { name: 'Braco', animal_type_id: 1 },
              { name: 'Bull Terrier', animal_type_id: 1 },
              { name: 'Bulldog', animal_type_id: 1 },
              { name: 'Chihuahueño', animal_type_id: 1 },
              { name: 'Chow chow', animal_type_id: 1 },
              { name: 'Cocker spaniel', animal_type_id: 1 },
              { name: 'Dobermann', animal_type_id: 1 },
              { name: 'Fox Terrier', animal_type_id: 1 },
              { name: 'Galgo', animal_type_id: 1 },
              { name: 'Golden retriever', animal_type_id: 1 },
              { name: 'Gran danés', animal_type_id: 1 },
              { name: 'Husky siberiano', animal_type_id: 1 },
              { name: 'Labrador', animal_type_id: 1 },
              { name: 'Mastín', animal_type_id: 1 },
              { name: 'Maltés', animal_type_id: 1 },
              { name: 'Pastor alemán', animal_type_id: 1 },
              { name: 'Pekinés', animal_type_id: 1 },
              { name: 'Perro de agua', animal_type_id: 1 },
              { name: 'Pinscher alemán', animal_type_id: 1 },
              { name: 'Pinscher miniatura', animal_type_id: 1 },
              { name: 'Pitbull', animal_type_id: 1 },
              { name: 'Podenco', animal_type_id: 1 },
              { name: 'Pug', animal_type_id: 1 },
              { name: 'Puli', animal_type_id: 1 },
              { name: 'Ratonero', animal_type_id: 1 },
              { name: 'Rottweiler', animal_type_id: 1 },
              { name: 'San Bernardo', animal_type_id: 1 },
              { name: 'Schnauzer', animal_type_id: 1 },
              { name: 'Siberian husky', animal_type_id: 1 },
              { name: 'Terrier', animal_type_id: 1 },
                { name: 'Criollo', animal_type_id: 2 },
                { name: 'Otra', animal_type_id: 2 },
                { name: 'Siamés', animal_type_id: 2 },
                { name: 'Siberiano', animal_type_id: 2 },
                { name: 'Oriental', animal_type_id: 2 },
                { name: 'Europeo Común', animal_type_id: 2 },
                { name: 'Abisinio', animal_type_id: 2 },
                { name: 'Azul ruso', animal_type_id: 2 },
                { name: 'Angora turco', animal_type_id: 2 },
                { name: 'Africano doméstico', animal_type_id: 2 },
                { name: 'American', animal_type_id: 2 },
                { name: 'Bengala', animal_type_id: 2 },
                { name: 'Dorado africano', animal_type_id: 2 },
                { name: 'Persa', animal_type_id: 2 },
                { name: 'Himalayo', animal_type_id: 2 }])

Province.create([{ name: 'Alajuela' },
                 { name: 'Cartago' },
                 { name: 'Guanacaste' },
                 { name: 'Heredia' },
                 { name: 'Limón' },
                 { name: 'Puntarenas' },
                 { name: 'San José' }])
